language: node_js
node_js:
  - stable
branches:
  only:
    - develop
before_install:
  - npm install -g hexo-cli
install:
  - npm install
script:
  - hexo clean
  - hexo generate
after_success:
  - git config --global user.name "kirk91"
  - git config --global user.email "kirk91.han@gmail.com"
  - echo ${GH_TOKEN}
  - sed -i'' "s~git@github.com:kirk91/kirk91.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/kirk91/kirk91.github.io.git~" _config.yml
  - cat _config.yml
  - hexo deploy
env:
  global:
    secure: TuFMdZDt9K1zPVDuuN7R831Xg3JDxlVavcrm3kYgLz/K1Euns+07MGGCGYHGZafgOeCNuIbD8AhcT26dn7V40M+toieMTcgafVeO4sAfVP5b8m9OkUMMD3YRo3k6PUOdRLOSata/7+xc64oLSEcHuM/o3I8VpisIfurrkWuHvdLWdzy3XwBFqTgLdfEo3KdoBLIXHMFn8Z/yK7wfwIEjpZ1Xnn9nCrnKZjkUtXitu+B7+5UleEBryx3T6y29A9N7GT/y7cJL7S3TBaKrYtBuwJ9xDtrzQ3ponR1lEKE09zatXSlk1xnqVvidE4tnsEPlWebNJ2Bbh910HLLNd4JNroDHvgZ5WSIF/pzjA+9eIvxKbY05I4O7FdTV/q0Km6iNKU+N4RkRz+sDeOldenbIknCXZEieOBqu+mCn9hool46U0ap4HDBL2znRWs8xJ4c0Vn4ebT0fm+pOiDVc3hl8g72WD+9dexvYQ5WC/c0tU2cQuCBmdEnbleIo4Vrv/NaFu57jsjZKBLLh2p/IX113mvinWjf/kAY6rZkQhzfte6rPJnjy0Cfb2EfkgItIz6CXBrtzRcpRVRyg3kkpxAkBTZzsRoooyNP/2mUKWtKgmK4LJNXuoLnqgsseddgfIFyCHba8WhWFqFa7ccjwnpxyQmiQM58=
